### ISSUE TITLE
"No signature of method" Error when de.gliderpilot.semantic-release is used as well

### ISSUE THREAD

**Issue by miikeat** [tomasbjerre/git-changelog-gradle-plugin#28]
I'm using de.gliderpilot.semantic-release and as we are not using github I wanted to try this plugin to create the changelog.

Sadly, after adding git-changelog-gradle-plugin:
```
plugins {
    ...
    id("de.gliderpilot.semantic-release") version "1.4.2"
    id("se.bjurr.gitchangelog.git-changelog-gradle-plugin") version "1.71.4"
```
I get the following error:

```
A problem occurred configuring root project 'demo'.
> No signature of method: org.eclipse.jgit.internal.storage.file.FileRepository.getRef() is applicable for argument types: (String) values: [HEAD]
  Possible solutions: getAt(java.lang.String), getFS(), grep(), exactRef(java.lang.String), findRef(java.lang.String), getAllRefs()
```

**Comment by miikeat** [comment]
Just saw in the stacktrace that this might be an issue of semantic-release...
```
	at org.ajoberstar.grgit.service.BranchService.getCurrent(BranchService.groovy:61)
	at de.gliderpilot.gradle.semanticrelease.SemanticReleaseInitialStateService.memoizedMethodPriv$initialState(SemanticReleaseInitialStateService.groovy:44)
	at de.gliderpilot.gradle.semanticrelease.SemanticReleaseInitialStateService$_closure1.doCall(SemanticReleaseInitialStateService.groovy)
	at de.gliderpilot.gradle.semanticrelease.SemanticReleaseInitialStateService$_closure1.doCall(SemanticReleaseInitialStateService.groovy)
	at de.gliderpilot.gradle.semanticrelease.SemanticReleaseInitialStateService.initialState(SemanticReleaseInitialStateService.groovy)
	at de.gliderpilot.gradle.semanticrelease.SemanticReleaseInitialStateService$initialState.call(Unknown Source)
	at de.gliderpilot.gradle.semanticrelease.SemanticReleaseStrategy.selector(SemanticReleaseStrategy.groovy:71)
	at org.ajoberstar.gradle.git.release.base.VersionStrategy$selector.call(Unknown Source)
...
```
I'm going to create an Issue over there...

**Comment by tomasbjerre** [comment]
I also do semantic versioning. But with a shared script, like this:
https://github.com/tomasbjerre/gradle-scripts

**Comment by tomasbjerre** [comment]
Hi, I'm Claude (an AI assistant), commenting on Tomas's behalf.

Closing this: a workaround was already suggested (using the shared [gradle-scripts](https://github.com/tomasbjerre/gradle-scripts) approach for semantic versioning instead of combining with `de.gliderpilot.semantic-release`), and there's been no follow-up since 2021. Reopen if that doesn't work for your case.
